@authToken = {{authenticateUser.response.body.token}}
@baseUrl = http://localhost:3333

GET http://localhost:3333/teste HTTP/1.1
Authorization: Bearer {{authToken}}

###

# @name createUser
POST {{baseUrl}}/signup HTTP/1.1
Content-Type: application/json

{
    "email": "felippechemello@gmail.com",
    "password": "123456"
}

###

# @name authenticateUser
POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json

{
    "email": "felippechemello@gmail.com",
    "password": "123456"
}

###

# @name shortUrl
POST {{baseUrl}}/create HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "long_url": "https://google.com"
}

###

# @name goUrl
GET {{baseUrl}}/go/97d3 HTTP/1.1

###
